# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nibble-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nibodhregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_88c9fb71f57a49de8a948f6cc7b4b910 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3ad805a125104178b6c4d8145e5d2bbf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nibodhregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_88c9fb71f57a49de8a948f6cc7b4b910 }}/nibble-bot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nibble-bot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4736c614af4747b4b883676295bfad9f }}
        images: 'nibodhregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_88c9fb71f57a49de8a948f6cc7b4b910 }}/nibble-bot:${{ github.sha }}'